<h4><span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="Gestion">Gestion</span> des <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="entrées">entr&eacute;es</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="utilisateur">utilisateur</span></h4><p><span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="Afin">Afin</span> de <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="permettre">permettre</span> aux <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="utilisateurs">utilisateurs</span> d&rsquo;<span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="interagir">interagir</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="avec">avec</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="votre">votre</span> application, <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="nous">nous</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="pouvons">pouvons</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="utiliser">utiliser</span> la directive <code>v-on</code> pour <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="attacher">attacher</span> des <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="écouteurs">&eacute;couteurs</span> d&rsquo;<span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="événements">&eacute;v&eacute;nements</span> qui <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="invoquent">invoquent</span> des <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="méthodes">m&eacute;thodes</span> sur nos instances de Vue :</p><pre>&lt;div id=&quot;app-5&quot;&gt;
  &lt;p&gt;{{ message }}&lt;/p&gt;
  &lt;button v-on:click=&quot;<span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="reverseMessage">reverseMessage</span>&quot;&gt;Message <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="retourné">retourn&eacute;</span>&lt;/button&gt;
&lt;/div&gt;</pre><pre>var <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="app5">app5</span> = new Vue({
  el: &#39;#app-5&#39;,
  data: {
    message: &#39;Hello Vue.js !&#39;
  },
  methods: {
    <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="reverseMessage">reverseMessage</span>: function () {
      this.message = this.message.split(&#39;&#39;).reverse().join(&#39;&#39;)
    }
  }
})</pre><p><span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="Notez">Notez</span> que <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="dans">dans</span> la <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="méthode">m&eacute;thode</span>, <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="nous">nous</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="avons">avons</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="seulement">seulement</span> mis &agrave; jour l&rsquo;<span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="état">&eacute;tat</span> de l&rsquo;application sans <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="toucher">toucher</span> au DOM &mdash; <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="toutes">toutes</span> les manipulations de DOM <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="sont">sont</span> prises en charge par Vue, <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="ainsi">ainsi</span> le code que <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="vous">vous</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="écrivez">&eacute;crivez</span> se <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="concentre">concentre</span> sur la <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="logique">logique</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="sous-jacente">sous-jacente</span>.</p><p>Vue <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="fournit">fournit</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="aussi">aussi</span> la directive <code>v-model</code> qui fait de la liaison de <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="données">donn&eacute;es</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="bidirectionnelle">bidirectionnelle</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="entre">entre</span> les champs d&rsquo;un <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="formulaire">formulaire</span> et l&rsquo;<span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="état">&eacute;tat</span> de l&rsquo;application. Une simple <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="formalité">formalit&eacute;</span> :</p><pre>&lt;div id=&quot;app-6&quot;&gt;
  &lt;p&gt;{{ message }}&lt;/p&gt;
  &lt;input v-model=&quot;message&quot;&gt;
&lt;/div&gt;</pre><pre>var <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="app6">app6</span> = new Vue({
  el: &#39;#app-6&#39;,
  data: {
    message: &#39;Hello Vue !&#39;
  }
})</pre><p>Si <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="l'utilisateur">l&#39;utilisateur</span> change la <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="valeur">valeur</span> de <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="l'input">l&#39;input</span> message change <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="aussi">aussi</span> et vis versa. C&#39;est ce qu&#39;on appelle le &quot;two way data-binding&quot;.</p>